import "./globals.css";

export const metadata = {
  title: "ObatKu - Aplikasi Manajemen Obat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-screen bg-slate-100 p-4 flex justify-center items-center text-slate-800">
        {children}
      </body>
    </html>
  );
}
